import fs from 'node:fs';
const root='artifacts/research/2026-09-07';
const refs=[
['R01','Stripe','https://stripe.com/','منتج','stripe-middle','مساحات المنتج بأحجام مختلفة','لقطة الدفع كبيرة بجانب مساحة أصغر للفوترة؛ التفاصيل المقربة تصنع الاختلاف داخل نفس القسم.','S03 / S06: شاشة حقيقية واسعة، وتفصيلة واحدة مكبرة خارجها. العرض يشرح سؤالًا واحدًا.','لا ننقل التدرجات أو أرقامهم أو نرسم واجهة تسويقية تشبه منتجنا.','مرئي — الجزء المصوّر فقط'],
['R02','Swiss Brut — live template','https://swissbrut.framer.website/','تكوين','swiss-live-desktop','الخط والمساحة هما التكوين','Desktop يجمع صورة كبيرة ونصفًا أبيض بكلمة ضخمة. Mobile ينقل الكلمة فوق الصورة بدل تصغير التقسيمة.','S02 / S14: كلمة مصرية قصيرة، مساحة بيضاء واسعة، استعارة الهاتف المعتمدة. قارن نسختين عند 1440 و390.','لا ننقل البورتريه أو الخط أو التأخير الكبير للوعد والزر المناسب لموقع وكالة.','مرئي — Desktop وMobile'],
['R03','Aceternity — Animated Tabs','https://ui.aceternity.com/components/tabs','تفاعل','aceternity-demo-desktop','مساحة عرض واحدة تتغير باختيار الزائر','ضغط Services أظهر لوحة Services في المقدمة. الصفحة تعرض أيضًا Copy prompt.','S06: فهرس الشاشات يبدّل لقطة حقيقية في مكان ثابت. انتقال صغير، عنوان واضح، وتكبير اختياري.','لا ننقل البنفسجي أو تكديس خمس شاشات أو UI المثال. على الهاتف يظل التدفق عموديًا.','مرئي + نقرة متحققة'],
['R04','Linear','https://linear.app/','تكوين','linear-middle','راحة بين الدليل والشرح','في الجزء المراجع: مساحة واسعة بين شريط الدليل وفقرة كبيرة، ثم رسومات تقنية بفواصل مشتركة.','S03 → S05: فقرة تعريفية هادئة يليها تقسيم تحريري؛ الحدود تنظّم القسم كله بدل بطاقة لكل جملة.','لقطة البداية كانت ناقصة؛ لا نعتمد عليها. لا dark theme أو شعارات عملاء غير حقيقية.','مرئي جزئيًا — وسط الصفحة'],
['R05','Landingfolio','https://www.landingfolio.com/components','مكتبات','landingfolio-middle','مكتبة لاختيار الأقسام ومقارنة الإيقاع','معرض لصفحات طويلة وفلاتر؛ بعض الصور لم تكتمل وظهر استطلاع جانبي أثناء الزيارة.','ابحث عن Product showcase / FAQ / pricing؛ احتفظ بمرجع واحد لكل وظيفة قبل تعديل القسم.','لا تنسخ صفحة كاملة ولا تعتبر screenshot دليلًا على interaction أو conversion.','المعرض مرئي؛ أمثلته ليست مدققة كلها'],
['R06','21st — Hero collection','https://21st.dev/community/components/s/hero','برومبتات','21st-top','مكونات مرتبطة ببرومبتات تنفيذ','المصدر الرسمي يعرض مكونات React وTailwind وبرومبتات AI. لقطة الصفحة الرئيسية حملت بطاقات ناقصة.','استعمل تصنيف Hero للعثور على بنية proof-first؛ أضف عقد Sparkle والعربية والموبايل قبل استخدام أي prompt.','لا تعتمد render ناقصًا كمرجع بصري؛ لا تثبّت أي مكون أو dependency تلقائيًا.','المصدر الرسمي مقروء؛ المعاينة البصرية جزئية'],
['R07','Framer — template marketplace','https://www.framer.com/marketplace/templates/categories/saas/','قوالب','framer-middle','مقارنة صفحات كاملة ثم فتح المعاينة','المعرض يعرض اتجاهات طباعية وتصويرية متعددة؛ تم فتح Swiss Brut وCofounder كمعاينات حية منفصلة.','مفيد لفحص انتقال Hero → proof → commercial calm، وليس لاختيار skin جاهز.','الترخيص لكل قالب وأصوله مستقل؛ لا يُفترض أن وصف Free يسمح بنقل كل الصور والكود.','معرض مرئي + معاينتان حيتان'],
['R08','Shadcnblocks — Feature 197','https://www.shadcnblocks.com/block/feature197','مكونات','feature197-top','Accordion مرتبط بصورة','الوصف الرسمي يربط قائمة قابلة للفتح بصورة كبيرة مجاورة. iframe المعاينة ظل في التحميل في اللقطة.','مرشح لـS06 إذا احتجنا تقليل طول قائمة الشاشات مع إبقاء الفائدة والصورة معًا.','هذه فكرة من الوصف؛ الأداء والتبديل الفعلي غير متحققين. لا نقترح استيراد الكود قبل المعاينة والترخيص.','وصف رسمي؛ demo غير متحقق'],
['R09','Magic UI — Hero Video Dialog','https://magicui.design/docs/components/hero-video-dialog','تفاعل','video-open','الفيديو يفتح عند الطلب','نقرة Play أظهرت overlay وزر إغلاق وإطار فيديو. الفيديو نفسه بقي أسود، ولم يُكتشف role=dialog.','12 video keys عندنا: poster حقيقي + زر فقط للحالة ready؛ Dialog دلالي وعودة التركيز وإيقاف الفيديو عند الإغلاق.','لا ننقل blur أو animation تلقائيًا. نتيجة فحص Escape غير كافية لإثبات الإغلاق لأن role لم يوجد أصلًا.','فتح بصري متحقق؛ التشغيل وaccessibility غير متحققين'],
['R10','Resend','https://resend.com/','منتج','resend-demo-desktop','التفاصيل تظهر حسب السياق','واجهة اختيار لغة فوق مساحة كود واحدة؛ نقطة تركيز ثابتة وتسميات واضحة. نقرة Python لم تغيّر الحالة المسجلة.','S06: فهرس واضح فوق الدليل، حالة نشطة محسوبة، مساحة ثابتة تمنع قفز الصفحة.','لا نزعم نجاح التبديل في تجربتنا ولا ننقل هوية المطورين أو كثرة tabs للموبايل.','تكوين مرئي؛ التفاعل غير مؤكد'],
['R11','Cofounder — live template','https://cofounder.framer.ai/','قوالب','cofounder-live-mobile','مثال مقارنة وحدود للمحاكاة','الهاتف: وعد، وصف، CTA ثم logos ثم صورة منتج مائلة وصغيرة. لا overflow في عرض 390 أثناء الفحص.','نأخذ وضوح ترتيب النص والزر، ثم نحسّن ترتيب Sparkle بوضع دليل مقروء قبل أي شريط دعم.','الميل يصغّر قراءة UI؛ لا ننقل dummy logos أو الأخضر أو الخلفية السوداء.','مرئي — Desktop وMobile'],
['R12','Aura — UI prompting guide','https://www.aura.build/learn/prompt-for-ui','برومبتات',null,'صياغة البرومبت بمراجع محددة','الدليل المفهرس يشرح توجيه UI بمراجع؛ الصفحة المباشرة لم تعط محتوى مقروءًا والزيارة انتهت بمهلة اتصال.','مرجع ثانوي لصياغة prompt يحدد section والمقاس والهدف والمصدر بدل «اعمل موقع premium».','لا نصفه بأنه اختُبر ولا ننقل وعود جودة التوليد. البديل المتاح: Copy prompt الظاهر في Aceternity.','فهرسة فقط — الوصول المباشر تعذّر']
].map(([id,name,url,category,shot,title,observed,adapt,avoid,evidence])=>({id,name,url,category,shot,title,observed,adapt,avoid,evidence}));
fs.writeFileSync(`${root}/references.json`,JSON.stringify(refs,null,2));
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const html=`<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sparkle — Visual Reference Board</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2faff;color:#03132e;font:17px/1.8 Arial,sans-serif}a{color:inherit}header,main,footer{max-width:1280px;margin:auto;padding:36px 24px}header{padding-top:64px}small,.eyebrow{font-size:13px;letter-spacing:.04em}h1{font-size:clamp(36px,5vw,70px);line-height:1.2;margin:20px 0}h2{font-size:25px;line-height:1.5;margin:0 0 12px}p{margin:10px 0}header p{max-width:780px}.rail{display:flex;gap:12px;flex-wrap:wrap;margin-top:24px}.rail a,button{border:2px solid #03132e;border-radius:8px;padding:10px 16px;background:white;font:inherit;cursor:pointer;text-decoration:none;min-height:46px}button[aria-pressed=true]{background:#01a2ff;box-shadow:3px 3px 0 #03132e}button:focus-visible,a:focus-visible{outline:3px solid #01a2ff;outline-offset:5px}nav{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:24px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:28px}.card{background:white;border:2px solid #03132e;border-radius:14px;overflow:hidden}.card[hidden]{display:none}.shot{display:block;background:#e5ecf4;height:300px;overflow:hidden;border-bottom:2px solid #03132e}.shot img{width:100%;height:100%;object-fit:contain}.empty{display:grid;place-items:center;height:300px;background:#e5ecf4}.body{padding:24px}.meta{display:flex;justify-content:space-between;color:#0c264b;font-size:13px;margin-bottom:12px}.source{display:inline-block;margin-top:16px;font-weight:bold}.label{font-weight:bold}.note{border-inline-start:4px solid #01a2ff;padding-inline-start:14px}.count{margin:0 0 20px}.priority{background:#03132e;color:white;padding:24px;border-radius:12px;margin-top:26px}.priority strong{color:#01a2ff}@media(max-width:760px){.grid{grid-template-columns:1fr}.shot,.empty{height:240px}header,main,footer{padding:24px 18px}.body{padding:20px}}
</style><header><div class="eyebrow">SPARKLE AUTO / RESEARCH / 07 SEP 2026</div><h1>دليل أقوى.<br>تكوين أجرأ. ضوضاء أقل.</h1><p>12 مرجعًا مختارًا للمكونات والقوالب والبرومبتات وتجارب المنتج. لكل مرجع: ما شاهدناه، أين نستفيد منه، وحدود الاقتباس. هذه لوحة بحث وليست موافقة على إعادة التصميم.</p><div class="rail"><a href="REFERENCE-RESEARCH.md">التقرير وخطة التحسين</a><a href="SPARKLE-ADAPTATION-PROMPTS.md">5 برومبتات أصلية</a><a href="screenshots/baseline-top.png">الموقع الحالي للمقارنة</a></div><div class="priority"><strong>الأولوية:</strong> دليل المنتج الحقيقي → ضبط طول عنوان الـHero → اختلاف مقاسات عرض الدليل → فهرس تفاعلي هادئ → فواصل طباعية تقلل تكرار البطاقات.</div></header><main><nav aria-label="تصفية المراجع">${['الكل',...new Set(refs.map(r=>r.category))].map((c,i)=>`<button data-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</nav><p class="count" aria-live="polite">12 مرجعًا</p><div class="grid">${refs.map(r=>`<article class="card" data-category="${r.category}">${r.shot?`<a class="shot" href="screenshots/${r.shot}.png" target="_blank" aria-label="تكبير لقطة ${esc(r.name)}"><img loading="lazy" src="screenshots/${r.shot}.png" alt="لقطة مرجعية من ${esc(r.name)} — ${esc(r.evidence)}"></a>`:'<div class="empty">لا توجد معاينة بصرية متحققة</div>'}<div class="body"><div class="meta"><span>${r.id} / ${r.category}</span><span dir="ltr">${esc(r.name)}</span></div><h2>${r.title}</h2><p class="note">${r.evidence}</p><p><span class="label">الملاحظة: </span>${r.observed}</p><p><span class="label">لـSparkle: </span>${r.adapt}</p><details><summary>حدود الاقتباس والتحقق</summary><p>${r.avoid}</p></details><a class="source" href="${r.url}" target="_blank" rel="noreferrer">افتح المصدر ↗</a></div></article>`).join('')}</div></main><footer>اللقطات من مواقع أصحابها للاطلاع الداخلي مع نسب المصدر؛ ليست أصول إنتاج. لم تُنسخ مكونات أو تُثبّت حزم. لم تُختبر معدلات التحويل أو الأداء أو إتاحة الوصول الشاملة للمراجع.</footer><script>document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let n=0;document.querySelectorAll('.card').forEach(c=>{c.hidden=b.dataset.filter!=='الكل'&&c.dataset.category!==b.dataset.filter;if(!c.hidden)n++});document.querySelector('.count').textContent=n+' مرجعًا'}));</script></html>`;
fs.writeFileSync(`${root}/reference-board.html`,html);
// Retain structural evidence, not copied page bodies or source snippets.
for(const file of ['browser-evidence.json','component-evidence.json','deep-evidence.json']){const path=`${root}/${file}`;const data=JSON.parse(fs.readFileSync(path));for(const x of data){delete x.text;delete x.visibleText;}fs.writeFileSync(path,JSON.stringify(data,null,2));}
