import {chromium} from '@playwright/test';import fs from 'node:fs';
const root='artifacts/review/site-walkthrough',url='https://sparkle-auto-landing-1bzl026dy-zodaayman2005-3362s-projects.vercel.app';
const b=await chromium.launch(),ctx=await b.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage(),cdp=await ctx.newCDPSession(p);
await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});
await p.addInitScript(()=>{window.__metrics={lcp:0,shiftSum:0};new PerformanceObserver(l=>l.getEntries().forEach(e=>window.__metrics.lcp=e.startTime)).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(l=>l.getEntries().forEach(e=>{if(!e.hadRecentInput)window.__metrics.shiftSum+=e.value})).observe({type:'layout-shift',buffered:true});});
await p.goto(url,{waitUntil:'load',timeout:60000});await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(2000);
const data=await p.evaluate(()=>({...window.__metrics,resources:performance.getEntriesByType('resource').map(r=>({url:r.name,bytes:r.transferSize,type:r.initiatorType})),heroCTA:document.querySelector('.hero .cta-row').getBoundingClientRect().top,proofTop:document.querySelector('.hero .hero-stage').getBoundingClientRect().top,metadata:[...document.querySelectorAll('meta[name],meta[property],link[rel=canonical],link[rel=alternate]')].map(e=>({name:e.name||e.getAttribute('property')||e.rel,content:e.content||e.href})),sections:[...document.querySelectorAll('main section')].map(s=>({id:s.id,class:s.className,height:Math.round(s.getBoundingClientRect().height),h:s.querySelector('h2')?.textContent})),smallTargets:[...document.querySelectorAll('a,button')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&(r.width<44||r.height<44)}).map(e=>({text:e.textContent.slice(0,50),height:e.getBoundingClientRect().height,width:e.getBoundingClientRect().width})).slice(0,30)}));
data.conditions='One cold-cache Chromium lab sample:390x844,CPU4x,RTT150ms,1.6Mbps download; not field CWV. shiftSum is sum of layout shifts, not windowed CLS.';
await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await cdp.send('Emulation.setCPUThrottlingRate',{rate:1});
for(const lang of ['ar','en']){await p.goto(url+(lang==='en'?'/en':'/'));for(const width of [390,1440]){await p.setViewportSize({width,height:900});for(const sel of ['#system','.audience','.trial-strip','#journey','#setup']){const el=p.locator(sel).first();if(!await el.count())continue;await el.evaluate(e=>window.scrollTo({top:e.getBoundingClientRect().top+scrollY-100,behavior:'instant'}));await p.waitForTimeout(250);await p.screenshot({path:`${root}/screenshots/${lang}-${width}-${sel.replace(/[.#]/g,'')}.png`});}}}
fs.writeFileSync(root+'/details.json',JSON.stringify(data,null,2));console.log(JSON.stringify({lcp:data.lcp,shiftSum:data.shiftSum,bytes:data.resources.reduce((s,x)=>s+x.bytes,0),heroCTA:data.heroCTA,proofTop:data.proofTop,smallTargets:data.smallTargets,sections:data.sections}));await b.close();
